/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.app.benefitEligibility.common

import enumeratum.{Enum, EnumEntry, PlayJsonEnum}

import scala.collection.immutable

sealed abstract class Country(override val entryName: String) extends EnumEntry

object Country extends Enum[Country] with PlayJsonEnum[Country] {
  val values: immutable.IndexedSeq[Country] = findValues

  case object AbroadNotKnown                     extends Country("ABROAD - NOT KNOWN")
  case object Afghanistan                        extends Country("AFGHANISTAN")
  case object Albania                            extends Country("ALBANIA")
  case object Alderney                           extends Country("ALDERNEY")
  case object Algeria                            extends Country("ALGERIA")
  case object AmericanSamoa                      extends Country("AMERICAN SAMOA")
  case object Andorra                            extends Country("ANDORRA")
  case object Angola                             extends Country("ANGOLA")
  case object Anguilla                           extends Country("ANGUILLA")
  case object AntarcticTerritoriesBritish        extends Country("ANTARCTIC TERRITORIES (BRITISH)")
  case object Antarctica                         extends Country("ANTARCTICA")
  case object Antigua                            extends Country("ANTIGUA")
  case object AntiguaAndBarbuda                  extends Country("ANTIGUA AND BARBUDA")
  case object AntillesNetherlands                extends Country("ANTILLES (NETHERLANDS)")
  case object ArabEmiratesUnited                 extends Country("ARAB EMIRATES (UNITED)")
  case object Argentina                          extends Country("ARGENTINA")
  case object Aruba                              extends Country("ARUBA")
  case object AscensionIsland                    extends Country("ASCENCION ISLAND")
  case object Australia                          extends Country("AUSTRALIA")
  case object Austria                            extends Country("AUSTRIA")
  case object Bahamas                            extends Country("BAHAMAS")
  case object Bahrain                            extends Country("BAHRAIN")
  case object Bangladesh                         extends Country("BANGLADESH")
  case object Barbados                           extends Country("BARBADOS")
  case object Barbuda                            extends Country("BARBUDA")
  case object Belgium                            extends Country("BELGIUM")
  case object Belize                             extends Country("BELIZE")
  case object Benin                              extends Country("BENIN")
  case object Bermuda                            extends Country("BERMUDA")
  case object Bhutan                             extends Country("BHUTAN")
  case object BissauGuinea                       extends Country("BISSAU (GUINEA)")
  case object Bolivia                            extends Country("BOLIVIA")
  case object Botswana                           extends Country("BOTSWANA")
  case object BouvetIsland                       extends Country("BOUVET ISLAND")
  case object Brazil                             extends Country("BRAZIL")
  case object BritishIndianOceanTerritories      extends Country("BRITISH INDIAN OCEAN TERRITORIES")
  case object Brunei                             extends Country("BRUNEI")
  case object Bulgaria                           extends Country("BULGARIA")
  case object BurkinaFaso                        extends Country("BURKINA FASO")
  case object Burma                              extends Country("BURMA")
  case object Burundi                            extends Country("BURUNDI")
  case object Cambodia                           extends Country("CAMBODIA")
  case object Cameroon                           extends Country("CAMEROON")
  case object Canada                             extends Country("CANADA")
  case object CapeVerdeIslands                   extends Country("CAPE VERDE ISLANDS")
  case object CaribbeanNetherlands               extends Country("CARIBBEAN NETHERLANDS")
  case object CaymanIslands                      extends Country("CAYMAN ISLANDS")
  case object CentralAfricanRepublic             extends Country("CENTRAL AFRICAN REPUBLIC")
  case object Chad                               extends Country("CHAD")
  case object ChannelIslands                     extends Country("CHANNEL ISLANDS")
  case object Chile                              extends Country("CHILE")
  case object ChinaPeoplesRepublic               extends Country("CHINA PEOPLES REPUBLIC")
  case object ChristmasIsland                    extends Country("CHRISTMAS ISLAND")
  case object CocosKeelingIslands                extends Country("COCOS (KEELING) ISLANDS")
  case object Colombia                           extends Country("COLOMBIA")
  case object CommonwealthOfDominica             extends Country("COMMONWEALTH OF DOMINICA")
  case object ComoroIslands                      extends Country("COMORO ISLANDS")
  case object Congo                              extends Country("CONGO")
  case object CookIslands                        extends Country("COOK ISLANDS")
  case object CostaRica                          extends Country("COSTA RICA")
  case object CoteDIvoire                        extends Country("COTE D'IVOIRE")
  case object Cuba                               extends Country("CUBA")
  case object Curacao                            extends Country("CURACAO")
  case object Cyprus                             extends Country("CYPRUS")
  case object CzechRepublic                      extends Country("CZECH REPUBLIC")
  case object Czechoslovakia                     extends Country("CZECHOSLOVAKIA")
  case object DemocraticRepublicOfCongo          extends Country("DEMOCRATIC REPUBLIC OF CONGO")
  case object DemocraticYemen                    extends Country("DEMOCRATIC YEMEN")
  case object Denmark                            extends Country("DENMARK")
  case object Djibouti                           extends Country("DJIBOUTI")
  case object DominicanRepublic                  extends Country("DOMINICAN REPUBLIC")
  case object EastGermany                        extends Country("EAST GERMANY")
  case object EastTimor                          extends Country("EAST TIMOR")
  case object Ecuador                            extends Country("ECUADOR")
  case object Egypt                              extends Country("EGYPT")
  case object ElSalvador                         extends Country("EL SALVADOR")
  case object England                            extends Country("ENGLAND")
  case object EquatorialGuinea                   extends Country("EQUATORIAL GUINEA")
  case object Eritrea                            extends Country("ERITREA")
  case object Ethiopia                           extends Country("ETHIOPIA")
  case object FalklandIslands                    extends Country("FALKLAND ISLANDS")
  case object FaroeIslands                       extends Country("FAROE ISLANDS")
  case object FederalRepOfYugoslavia             extends Country("FEDERAL REP OF YUGOSLAVIA")
  case object Fiji                               extends Country("FIJI")
  case object Finland                            extends Country("FINLAND")
  case object FormerYugRepOfMacedonia            extends Country("FORMER YUG REP OF MACEDONIA")
  case object France                             extends Country("FRANCE")
  case object FrenchGuiana                       extends Country("FRENCH GUIANA")
  case object FrenchOverseasDepartment           extends Country("FRENCH OVERSEAS DEPARTMENT")
  case object FrenchPolynesia                    extends Country("FRENCH POLYNESIA")
  case object FrenchSouthernTerritories          extends Country("FRENCH SOUTHERN TERRITORIES")
  case object Gabon                              extends Country("GABON")
  case object Gambia                             extends Country("GAMBIA")
  case object Germany                            extends Country("GERMANY")
  case object Ghana                              extends Country("GHANA")
  case object Gibraltar                          extends Country("GIBRALTAR")
  case object GreatBritain                       extends Country("GREAT BRITAIN")
  case object Greece                             extends Country("GREECE")
  case object Greenland                          extends Country("GREENLAND")
  case object Grenada                            extends Country("GRENADA")
  case object Guadeloupe                         extends Country("GUADELOUPE")
  case object Guam                               extends Country("GUAM")
  case object Guatemala                          extends Country("GUATEMALA")
  case object Guernsey                           extends Country("GUERNSEY")
  case object Guinea                             extends Country("GUINEA")
  case object Guyana                             extends Country("GUYANA")
  case object Haiti                              extends Country("HAITI")
  case object HeardIslandAndMcdonaldIslands      extends Country("HEARD ISLAND AND MCDONALD ISLANDS")
  case object Honduras                           extends Country("HONDURAS")
  case object HongKong                           extends Country("HONG KONG")
  case object Hungary                            extends Country("HUNGARY")
  case object Iceland                            extends Country("ICELAND")
  case object India                              extends Country("INDIA")
  case object Indonesia                          extends Country("INDONESIA")
  case object Iran                               extends Country("IRAN")
  case object Iraq                               extends Country("IRAQ")
  case object IsleOfMan                          extends Country("ISLE OF MAN")
  case object Israel                             extends Country("ISRAEL")
  case object Italy                              extends Country("ITALY")
  case object Jamaica                            extends Country("JAMAICA")
  case object Japan                              extends Country("JAPAN")
  case object Jersey                             extends Country("JERSEY")
  case object Jordan                             extends Country("JORDAN")
  case object Kampuchea                          extends Country("KAMPUCHEA")
  case object Kenya                              extends Country("KENYA")
  case object Kiribati                           extends Country("KIRIBATI")
  case object Kuwait                             extends Country("KUWAIT")
  case object Laos                               extends Country("LAOS")
  case object Lebanon                            extends Country("LEBANON")
  case object Lesotho                            extends Country("LESOTHO")
  case object Liberia                            extends Country("LIBERIA")
  case object Libya                              extends Country("LIBYA")
  case object Liechtenstein                      extends Country("LIECHTENSTEIN")
  case object Luxembourg                         extends Country("LUXEMBOURG")
  case object Macau                              extends Country("MACAU")
  case object Madagascar                         extends Country("MADAGASCAR")
  case object Malawi                             extends Country("MALAWI")
  case object Malaysia                           extends Country("MALAYSIA")
  case object MaldiveIslands                     extends Country("MALDIVE ISLANDS")
  case object Mali                               extends Country("MALI")
  case object Malta                              extends Country("MALTA")
  case object MarshallIslands                    extends Country("MARSHALL ISLANDS")
  case object Martinique                         extends Country("MARTINIQUE")
  case object Mauritania                         extends Country("MAURITANIA")
  case object Mauritius                          extends Country("MAURITIUS")
  case object Mayotte                            extends Country("MAYOTTE")
  case object Mexico                             extends Country("MEXICO")
  case object MicronesiaFederationOf             extends Country("MICRONESIA FEDERATION OF")
  case object Monaco                             extends Country("MONACO")
  case object Mongolia                           extends Country("MONGOLIA")
  case object Montserrat                         extends Country("MONTSERRAT")
  case object Morocco                            extends Country("MOROCCO")
  case object Mozambique                         extends Country("MOZAMBIQUE")
  case object Myanmar                            extends Country("MYANMAR")
  case object Namibia                            extends Country("NAMIBIA")
  case object Nauru                              extends Country("NAURU")
  case object Nepal                              extends Country("NEPAL")
  case object Netherlands                        extends Country("NETHERLANDS")
  case object NevisStKittsNevis                  extends Country("NEVIS,ST KITTS-NEVIS")
  case object NewCaledonia                       extends Country("NEW CALEDONIA")
  case object NewZealand                         extends Country("NEW ZEALAND")
  case object Nicaragua                          extends Country("NICARAGUA")
  case object Niger                              extends Country("NIGER")
  case object Nigeria                            extends Country("NIGERIA")
  case object Niue                               extends Country("NIUE")
  case object NorfolkIsland                      extends Country("NORFOLK ISLAND")
  case object NorthKorea                         extends Country("NORTH KOREA")
  case object NorthMacedonia                     extends Country("NORTH MACEDONIA")
  case object NorthernIreland                    extends Country("NORTHERN IRELAND")
  case object NorthernMarianaIslands             extends Country("NORTHERN MARIANA ISLANDS")
  case object Norway                             extends Country("NORWAY")
  case object NotSpecifiedOrNotUsed              extends Country("NOT SPECIFIED OR NOT USED")
  case object NotYetRecorded                     extends Country("NOT YET RECORDED")
  case object Oman                               extends Country("OMAN")
  case object Pakistan                           extends Country("PAKISTAN")
  case object Palau                              extends Country("PALAU")
  case object Panama                             extends Country("PANAMA")
  case object PapuaNewGuinea                     extends Country("PAPUA NEW GUINEA")
  case object Paraguay                           extends Country("PARAGUAY")
  case object Peru                               extends Country("PERU")
  case object Philippines                        extends Country("PHILIPPINES")
  case object Pitcairn                           extends Country("PITCAIRN")
  case object Poland                             extends Country("POLAND")
  case object Portugal                           extends Country("PORTUGAL")
  case object PrincipeAndSaoTome                 extends Country("PRINCIPE AND SAO TOME")
  case object PuertoRico                         extends Country("PUERTO RICO")
  case object Qatar                              extends Country("QATAR")
  case object RepOfBosniaHerzegovina             extends Country("REP OF BOSNIA-HERZEGOVINA")
  case object RepublicOfArmenia                  extends Country("REPUBLIC OF ARMENIA")
  case object RepublicOfAzerbaijan               extends Country("REPUBLIC OF AZERBAIJAN")
  case object RepublicOfBelarus                  extends Country("REPUBLIC OF BELARUS")
  case object RepublicOfCroatia                  extends Country("REPUBLIC OF CROATIA")
  case object RepublicOfEstonia                  extends Country("REPUBLIC OF ESTONIA")
  case object RepublicOfGeorgia                  extends Country("REPUBLIC OF GEORGIA")
  case object RepublicOfIreland                  extends Country("REPUBLIC OF IRELAND")
  case object RepublicOfKazakhstan               extends Country("REPUBLIC OF KAZAKHSTAN")
  case object RepublicOfKosovo                   extends Country("REPUBLIC OF KOSOVO")
  case object RepublicOfKyrgyzstan               extends Country("REPUBLIC OF KYRGYZSTAN")
  case object RepublicOfLatvia                   extends Country("REPUBLIC OF LATVIA")
  case object RepublicOfLithuania                extends Country("REPUBLIC OF LITHUANIA")
  case object RepublicOfMoldova                  extends Country("REPUBLIC OF MOLDOVA")
  case object RepublicOfMontenegro               extends Country("REPUBLIC OF MONTENEGRO")
  case object RepublicOfSerbia                   extends Country("REPUBLIC OF SERBIA")
  case object RepublicOfSlovenia                 extends Country("REPUBLIC OF SLOVENIA")
  case object RepublicOfTajikistan               extends Country("REPUBLIC OF TAJIKISTAN")
  case object RepublicOfTurkmenistan             extends Country("REPUBLIC OF TURKMENISTAN")
  case object RepublicOfUzbekistan               extends Country("REPUBLIC OF UZBEKISTAN")
  case object RepublicOfYemen                    extends Country("REPUBLIC OF YEMEN")
  case object Reunion                            extends Country("REUNION")
  case object Romania                            extends Country("ROMANIA")
  case object Russia                             extends Country("RUSSIA")
  case object RussianFederation                  extends Country("RUSSIAN FEDERATION")
  case object Rwanda                             extends Country("RWANDA")
  case object Sabah                              extends Country("SABAH")
  case object SaintPierreAndMiquelon             extends Country("SAINT PIERRE AND MIQUELON")
  case object Samoa                              extends Country("SAMOA")
  case object SanMarino                          extends Country("SAN MARINO")
  case object Sarawak                            extends Country("SARAWAK")
  case object Sark                               extends Country("SARK")
  case object SaudiArabia                        extends Country("SAUDI ARABIA")
  case object Scotland                           extends Country("SCOTLAND")
  case object Senegal                            extends Country("SENEGAL")
  case object Seychelles                         extends Country("SEYCHELLES")
  case object Sharjah                            extends Country("SHARJAH")
  case object SierraLeone                        extends Country("SIERRA LEONE")
  case object Singapore                          extends Country("SINGAPORE")
  case object SlovakRepublic                     extends Country("SLOVAK REPUBLIC")
  case object SolomonIslands                     extends Country("SOLOMON ISLANDS")
  case object Somalia                            extends Country("SOMALIA")
  case object SouthAfrica                        extends Country("SOUTH AFRICA")
  case object SouthGeorgiaAndSouthSandwichIsland extends Country("SOUTH GEORGIA AND SOUTH SANDWICH ISLAND")
  case object SouthKorea                         extends Country("SOUTH KOREA")
  case object Spain                              extends Country("SPAIN")
  case object SriLanka                           extends Country("SRI LANKA")
  case object StHelenaAndDepnds                  extends Country("ST HELENA & DEPNDS")
  case object StLucia                            extends Country("ST LUCIA")
  case object StMartins                          extends Country("ST MARTINS")
  case object StVincentAndGrenadines             extends Country("ST VINCENT & GRENADINES")
  case object Stateless                          extends Country("STATELESS")
  case object Sudan                              extends Country("SUDAN")
  case object Surinam                            extends Country("SURINAM")
  case object SvalbardAndJanMayen                extends Country("SVALBARD AND JAN MAYEN")
  case object Swaziland                          extends Country("SWAZILAND")
  case object Sweden                             extends Country("SWEDEN")
  case object Switzerland                        extends Country("SWITZERLAND")
  case object Syria                              extends Country("SYRIA")
  case object Tahiti                             extends Country("TAHITI")
  case object Taiwan                             extends Country("TAIWAN")
  case object Tanzania                           extends Country("TANZANIA")
  case object Thailand                           extends Country("THAILAND")
  case object Togo                               extends Country("TOGO")
  case object Tokelau                            extends Country("TOKELAU")
  case object Tonga                              extends Country("TONGA")
  case object Tours                              extends Country("TOURS")
  case object TrinidadAndTobago                  extends Country("TRINIDAD & TOBAGO")
  case object TristanDaCuhna                     extends Country("TRISTAN DA CUHNA")
  case object Tunisia                            extends Country("TUNISIA")
  case object Turkey                             extends Country("TURKEY")
  case object TurksAndCaicosIslands              extends Country("TURKS & CAICOS ISLANDS")
  case object Tuvalu                             extends Country("TUVALU")
  case object Uganda                             extends Country("UGANDA")
  case object Ukraine                            extends Country("UKRAINE")
  case object UnitedStatesMinorOutlyingIslands   extends Country("UNITED STATES MINOR OUTLYING ISLANDS")
  case object Uruguay                            extends Country("URUGUAY")
  case object USA                                extends Country("USA")
  case object USSR                               extends Country("USSR")
  case object Vanuatu                            extends Country("VANUATU")
  case object VaticanCityState                   extends Country("VATICAN CITY STATE")
  case object Venezuela                          extends Country("VENEZUELA")
  case object Vietnam                            extends Country("VIETNAM")
  case object VirginIslandsBritish               extends Country("VIRGIN ISLANDS (BRITISH)")
  case object VirginIslandsUSA                   extends Country("VIRGIN ISLANDS (USA)")
  case object Wales                              extends Country("WALES")
  case object WallisAndFutuna                    extends Country("WALLIS AND FUTUNA")
  case object WesternSahara                      extends Country("WESTERN SAHARA")
  case object WesternSamoa                       extends Country("WESTERN SAMOA")
  case object Yugoslavia                         extends Country("YUGOSLAVIA")
  case object Zaire                              extends Country("ZAIRE")
  case object Zambia                             extends Country("ZAMBIA")
  case object Zimbabwe                           extends Country("ZIMBABWE")
  case object NorthernPartOfCyprus               extends Country("NORTHERN PART OF CYPRUS")
}
