/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.app.benefitEligibility.integration.outbound.liabilitySummaryDetails.model.response.enums

import enumeratum.{Enum, EnumEntry, PlayJsonEnum}

import scala.collection.immutable

sealed abstract class EnumCountry(override val entryName: String) extends EnumEntry

object EnumCountry extends Enum[EnumCountry] with PlayJsonEnum[EnumCountry] {
  val values: immutable.IndexedSeq[EnumCountry] = findValues

  case object AbroadNotKnown                     extends EnumCountry("ABROAD - NOT KNOWN")
  case object Afghanistan                        extends EnumCountry("AFGHANISTAN")
  case object Albania                            extends EnumCountry("ALBANIA")
  case object Alderney                           extends EnumCountry("ALDERNEY")
  case object Algeria                            extends EnumCountry("ALGERIA")
  case object AmericanSamoa                      extends EnumCountry("AMERICAN SAMOA")
  case object Andorra                            extends EnumCountry("ANDORRA")
  case object Angola                             extends EnumCountry("ANGOLA")
  case object Anguilla                           extends EnumCountry("ANGUILLA")
  case object Antarctic_territories_british      extends EnumCountry("ANTARCTIC TERRITORIES (BRITISH)")
  case object Antarctica                         extends EnumCountry("ANTARCTICA")
  case object Antigua                            extends EnumCountry("ANTIGUA")
  case object Antigua_and_barbuda                extends EnumCountry("ANTIGUA AND BARBUDA")
  case object Antilles_netherlands               extends EnumCountry("ANTILLES (NETHERLANDS)")
  case object Arab_emirates_united               extends EnumCountry("ARAB EMIRATES (UNITED)")
  case object Argentina                          extends EnumCountry("ARGENTINA")
  case object Aruba                              extends EnumCountry("ARUBA")
  case object AscencionIsland                    extends EnumCountry("ASCENCION ISLAND")
  case object Australia                          extends EnumCountry("AUSTRALIA")
  case object Austria                            extends EnumCountry("AUSTRIA")
  case object Bahamas                            extends EnumCountry("BAHAMAS")
  case object Bahrain                            extends EnumCountry("BAHRAIN")
  case object Bangladesh                         extends EnumCountry("BANGLADESH")
  case object Barbados                           extends EnumCountry("BARBADOS")
  case object Barbuda                            extends EnumCountry("BARBUDA")
  case object Belgium                            extends EnumCountry("BELGIUM")
  case object Belize                             extends EnumCountry("BELIZE")
  case object Benin                              extends EnumCountry("BENIN")
  case object Bermuda                            extends EnumCountry("BERMUDA")
  case object Bhutan                             extends EnumCountry("BHUTAN")
  case object BissauGuinea                       extends EnumCountry("BISSAU (GUINEA)")
  case object Bolivia                            extends EnumCountry("BOLIVIA")
  case object Botswana                           extends EnumCountry("BOTSWANA")
  case object BouvetIsland                       extends EnumCountry("BOUVET ISLAND")
  case object Brazil                             extends EnumCountry("BRAZIL")
  case object BritishIndianOceanTerritories      extends EnumCountry("BRITISH INDIAN OCEAN TERRITORIES")
  case object Brunei                             extends EnumCountry("BRUNEI")
  case object Bulgaria                           extends EnumCountry("BULGARIA")
  case object BurkinaFaso                        extends EnumCountry("BURKINA FASO")
  case object Burma                              extends EnumCountry("BURMA")
  case object Burundi                            extends EnumCountry("BURUNDI")
  case object Cambodia                           extends EnumCountry("CAMBODIA")
  case object Cameroon                           extends EnumCountry("CAMEROON")
  case object Canada                             extends EnumCountry("CANADA")
  case object CapeVerdeIslands                   extends EnumCountry("CAPE VERDE ISLANDS")
  case object CaribbeanNetherlands               extends EnumCountry("CARIBBEAN NETHERLANDS")
  case object CaymanIslands                      extends EnumCountry("CAYMAN ISLANDS")
  case object CentralAfricanRepublic             extends EnumCountry("CENTRAL AFRICAN REPUBLIC")
  case object Chad                               extends EnumCountry("CHAD")
  case object ChannelIslands                     extends EnumCountry("CHANNEL ISLANDS")
  case object Chile                              extends EnumCountry("CHILE")
  case object ChinaPeoplesRepublic               extends EnumCountry("CHINA PEOPLES REPUBLIC")
  case object ChristmasIsland                    extends EnumCountry("CHRISTMAS ISLAND")
  case object CocosKeelingIslands                extends EnumCountry("COCOS (KEELING) ISLANDS")
  case object Colombia                           extends EnumCountry("COLOMBIA")
  case object CommonwealthOfDominica             extends EnumCountry("COMMONWEALTH OF DOMINICA")
  case object ComoroIslands                      extends EnumCountry("COMORO ISLANDS")
  case object Congo                              extends EnumCountry("CONGO")
  case object CookIslands                        extends EnumCountry("COOK ISLANDS")
  case object CostaRica                          extends EnumCountry("COSTA RICA")
  case object CoteDivoire                        extends EnumCountry("COTE D'IVOIRE")
  case object Cuba                               extends EnumCountry("CUBA")
  case object Curacao                            extends EnumCountry("CURACAO")
  case object Cyprus                             extends EnumCountry("CYPRUS")
  case object CzechRepublic                      extends EnumCountry("CZECH REPUBLIC")
  case object Czechoslovakia                     extends EnumCountry("CZECHOSLOVAKIA")
  case object DemocraticRepublicOfCongo          extends EnumCountry("DEMOCRATIC REPUBLIC OF CONGO")
  case object DemocraticYemen                    extends EnumCountry("DEMOCRATIC YEMEN")
  case object Denmark                            extends EnumCountry("DENMARK")
  case object Djibouti                           extends EnumCountry("DJIBOUTI")
  case object DominicanRepublic                  extends EnumCountry("DOMINICAN REPUBLIC")
  case object EastGermany                        extends EnumCountry("EAST GERMANY")
  case object EastTimor                          extends EnumCountry("EAST TIMOR")
  case object Ecuador                            extends EnumCountry("ECUADOR")
  case object Egypt                              extends EnumCountry("EGYPT")
  case object ElSalvador                         extends EnumCountry("EL SALVADOR")
  case object England                            extends EnumCountry("ENGLAND")
  case object EquatorialGuinea                   extends EnumCountry("EQUATORIAL GUINEA")
  case object Eritrea                            extends EnumCountry("ERITREA")
  case object Ethiopia                           extends EnumCountry("ETHIOPIA")
  case object FalklandIslands                    extends EnumCountry("FALKLAND ISLANDS")
  case object FaroeIslands                       extends EnumCountry("FAROE ISLANDS")
  case object FederalRepOfYugoslavia             extends EnumCountry("FEDERAL REP OF YUGOSLAVIA")
  case object Fiji                               extends EnumCountry("FIJI")
  case object Finland                            extends EnumCountry("FINLAND")
  case object FormerYugRepOfMacedonia            extends EnumCountry("FORMER YUG REP OF MACEDONIA")
  case object France                             extends EnumCountry("FRANCE")
  case object FrenchGuiana                       extends EnumCountry("FRENCH GUIANA")
  case object FrenchOverseasDepartment           extends EnumCountry("FRENCH OVERSEAS DEPARTMENT")
  case object FrenchPolynesia                    extends EnumCountry("FRENCH POLYNESIA")
  case object FrenchSouthernTerritories          extends EnumCountry("FRENCH SOUTHERN TERRITORIES")
  case object Gabon                              extends EnumCountry("GABON")
  case object Gambia                             extends EnumCountry("GAMBIA")
  case object Germany                            extends EnumCountry("GERMANY")
  case object Ghana                              extends EnumCountry("GHANA")
  case object Gibraltar                          extends EnumCountry("GIBRALTAR")
  case object GreatBritain                       extends EnumCountry("GREAT BRITAIN")
  case object Greece                             extends EnumCountry("GREECE")
  case object Greenland                          extends EnumCountry("GREENLAND")
  case object Grenada                            extends EnumCountry("GRENADA")
  case object Guadeloupe                         extends EnumCountry("GUADELOUPE")
  case object Guam                               extends EnumCountry("GUAM")
  case object Guatemala                          extends EnumCountry("GUATEMALA")
  case object Guernsey                           extends EnumCountry("GUERNSEY")
  case object Guinea                             extends EnumCountry("GUINEA")
  case object Guyana                             extends EnumCountry("GUYANA")
  case object Haiti                              extends EnumCountry("HAITI")
  case object HeardIslandAndMcdonaldIslands      extends EnumCountry("HEARD ISLAND AND MCDONALD ISLANDS")
  case object Honduras                           extends EnumCountry("HONDURAS")
  case object Hongkong                           extends EnumCountry("HONG KONG")
  case object Hungary                            extends EnumCountry("HUNGARY")
  case object Iceland                            extends EnumCountry("ICELAND")
  case object India                              extends EnumCountry("INDIA")
  case object Indonesia                          extends EnumCountry("INDONESIA")
  case object Iran                               extends EnumCountry("IRAN")
  case object Iraq                               extends EnumCountry("IRAQ")
  case object IsleOfMan                          extends EnumCountry("ISLE OF MAN")
  case object Israel                             extends EnumCountry("ISRAEL")
  case object Italy                              extends EnumCountry("ITALY")
  case object Jamaica                            extends EnumCountry("JAMAICA")
  case object Japan                              extends EnumCountry("JAPAN")
  case object Jersey                             extends EnumCountry("JERSEY")
  case object Jordan                             extends EnumCountry("JORDAN")
  case object Kampuchea                          extends EnumCountry("KAMPUCHEA")
  case object Kenya                              extends EnumCountry("KENYA")
  case object Kiribati                           extends EnumCountry("KIRIBATI")
  case object Kuwait                             extends EnumCountry("KUWAIT")
  case object Laos                               extends EnumCountry("LAOS")
  case object Lebanon                            extends EnumCountry("LEBANON")
  case object Lesotho                            extends EnumCountry("LESOTHO")
  case object Liberia                            extends EnumCountry("LIBERIA")
  case object Libya                              extends EnumCountry("LIBYA")
  case object Liechtenstein                      extends EnumCountry("LIECHTENSTEIN")
  case object Luxembourg                         extends EnumCountry("LUXEMBOURG")
  case object Macau                              extends EnumCountry("MACAU")
  case object Madagascar                         extends EnumCountry("MADAGASCAR")
  case object Malawi                             extends EnumCountry("MALAWI")
  case object Malaysia                           extends EnumCountry("MALAYSIA")
  case object MaldiveIslands                     extends EnumCountry("MALDIVE ISLANDS")
  case object Mali                               extends EnumCountry("MALI")
  case object Malta                              extends EnumCountry("MALTA")
  case object MarshallIslands                    extends EnumCountry("MARSHALL ISLANDS")
  case object Martinique                         extends EnumCountry("MARTINIQUE")
  case object Mauritania                         extends EnumCountry("MAURITANIA")
  case object Mauritius                          extends EnumCountry("MAURITIUS")
  case object Mayotte                            extends EnumCountry("MAYOTTE")
  case object Mexico                             extends EnumCountry("MEXICO")
  case object MicronesiaFederationOf             extends EnumCountry("MICRONESIA FEDERATION OF")
  case object Monaco                             extends EnumCountry("MONACO")
  case object Mongolia                           extends EnumCountry("MONGOLIA")
  case object Montserrat                         extends EnumCountry("MONTSERRAT")
  case object Morocco                            extends EnumCountry("MOROCCO")
  case object Mozambique                         extends EnumCountry("MOZAMBIQUE")
  case object Myanmar                            extends EnumCountry("MYANMAR")
  case object Namibia                            extends EnumCountry("NAMIBIA")
  case object Nauru                              extends EnumCountry("NAURU")
  case object Nepal                              extends EnumCountry("NEPAL")
  case object Netherlands                        extends EnumCountry("NETHERLANDS")
  case object NevisStKittsNevis                  extends EnumCountry("NEVIS,ST KITTS-NEVIS")
  case object NewCaledonia                       extends EnumCountry("NEW CALEDONIA")
  case object NewZealand                         extends EnumCountry("NEW ZEALAND")
  case object Nicaragua                          extends EnumCountry("NICARAGUA")
  case object Niger                              extends EnumCountry("NIGER")
  case object Nigeria                            extends EnumCountry("NIGERIA")
  case object Niue                               extends EnumCountry("NIUE")
  case object NorfolkIsland                      extends EnumCountry("NORFOLK ISLAND")
  case object NorthKorea                         extends EnumCountry("NORTH KOREA")
  case object NorthMacedonia                     extends EnumCountry("NORTH MACEDONIA")
  case object NorthernIreland                    extends EnumCountry("NORTHERN IRELAND")
  case object NorthernMarianaIslands             extends EnumCountry("NORTHERN MARIANA ISLANDS")
  case object Norway                             extends EnumCountry("NORWAY")
  case object NotSpecifiedOrNotUsed              extends EnumCountry("NOT SPECIFIED OR NOT USED")
  case object NotYetRecorded                     extends EnumCountry("NOT YET RECORDED")
  case object Oman                               extends EnumCountry("OMAN")
  case object Pakistan                           extends EnumCountry("PAKISTAN")
  case object Palau                              extends EnumCountry("PALAU")
  case object Panama                             extends EnumCountry("PANAMA")
  case object PapuaNewGuinea                     extends EnumCountry("PAPUA NEW GUINEA")
  case object Paraguay                           extends EnumCountry("PARAGUAY")
  case object Peru                               extends EnumCountry("PERU")
  case object Philippines                        extends EnumCountry("PHILIPPINES")
  case object Pitcairn                           extends EnumCountry("PITCAIRN")
  case object Poland                             extends EnumCountry("POLAND")
  case object Portugal                           extends EnumCountry("PORTUGAL")
  case object PrincipeAndSaoTome                 extends EnumCountry("PRINCIPE AND SAO TOME")
  case object PuertoRico                         extends EnumCountry("PUERTO RICO")
  case object Qatar                              extends EnumCountry("QATAR")
  case object RepOfBosniaHerzegovina             extends EnumCountry("REP OF BOSNIA-HERZEGOVINA")
  case object RepublicOfArmenia                  extends EnumCountry("REPUBLIC OF ARMENIA")
  case object RepublicOfAzerbaijan               extends EnumCountry("REPUBLIC OF AZERBAIJAN")
  case object RepublicOfBelarus                  extends EnumCountry("REPUBLIC OF BELARUS")
  case object RepublicOfCroatia                  extends EnumCountry("REPUBLIC OF CROATIA")
  case object RepublicOfEstonia                  extends EnumCountry("REPUBLIC OF ESTONIA")
  case object RepublicOfGeorgia                  extends EnumCountry("REPUBLIC OF GEORGIA")
  case object RepublicOfIreland                  extends EnumCountry("REPUBLIC OF IRELAND")
  case object RepublicOfKazakhstan               extends EnumCountry("REPUBLIC OF KAZAKHSTAN")
  case object RepublicOfKosovo                   extends EnumCountry("REPUBLIC OF KOSOVO")
  case object RepublicOfKyrgyzstan               extends EnumCountry("REPUBLIC OF KYRGYZSTAN")
  case object RepublicOfLatvia                   extends EnumCountry("REPUBLIC OF LATVIA")
  case object RepublicOfLithuania                extends EnumCountry("REPUBLIC OF LITHUANIA")
  case object RepublicOfMoldova                  extends EnumCountry("REPUBLIC OF MOLDOVA")
  case object RepublicOfMontenegro               extends EnumCountry("REPUBLIC OF MONTENEGRO")
  case object RepublicOfSerbia                   extends EnumCountry("REPUBLIC OF SERBIA")
  case object RepublicOfSlovenia                 extends EnumCountry("REPUBLIC OF SLOVENIA")
  case object RepublicOfTajikistan               extends EnumCountry("REPUBLIC OF TAJIKISTAN")
  case object RepublicOfTurkmenistan             extends EnumCountry("REPUBLIC OF TURKMENISTAN")
  case object RepublicOfUzbekistan               extends EnumCountry("REPUBLIC OF UZBEKISTAN")
  case object RepublicOfYemen                    extends EnumCountry("REPUBLIC OF YEMEN")
  case object Reunion                            extends EnumCountry("REUNION")
  case object Romania                            extends EnumCountry("ROMANIA")
  case object Russia                             extends EnumCountry("RUSSIA")
  case object RussianFederation                  extends EnumCountry("RUSSIAN FEDERATION")
  case object Rwanda                             extends EnumCountry("RWANDA")
  case object Sabah                              extends EnumCountry("SABAH")
  case object SaintPierreAndMiquelon             extends EnumCountry("SAINT PIERRE AND MIQUELON")
  case object Samoa                              extends EnumCountry("SAMOA")
  case object SanMarino                          extends EnumCountry("SAN MARINO")
  case object Sarawak                            extends EnumCountry("SARAWAK")
  case object Sark                               extends EnumCountry("SARK")
  case object SaudiArabia                        extends EnumCountry("SAUDI ARABIA")
  case object Scotland                           extends EnumCountry("SCOTLAND")
  case object Senegal                            extends EnumCountry("SENEGAL")
  case object Seychelles                         extends EnumCountry("SEYCHELLES")
  case object Sharjah                            extends EnumCountry("SHARJAH")
  case object SierraLeone                        extends EnumCountry("SIERRA LEONE")
  case object Singapore                          extends EnumCountry("SINGAPORE")
  case object SlovakRepublic                     extends EnumCountry("SLOVAK REPUBLIC")
  case object SolomonIslands                     extends EnumCountry("SOLOMON ISLANDS")
  case object Somalia                            extends EnumCountry("SOMALIA")
  case object SouthAfrica                        extends EnumCountry("SOUTH AFRICA")
  case object SouthGeorgiaAndSouthSandwichIsland extends EnumCountry("SOUTH GEORGIA AND SOUTH SANDWICH ISLAND")
  case object SouthKorea                         extends EnumCountry("SOUTH KOREA")
  case object Spain                              extends EnumCountry("SPAIN")
  case object SriLanka                           extends EnumCountry("SRI LANKA")
  case object StHelenaDepnds                     extends EnumCountry("ST HELENA & DEPNDS")
  case object StLucia                            extends EnumCountry("ST LUCIA")
  case object StMartins                          extends EnumCountry("ST MARTINS")
  case object StVincentGrenadines                extends EnumCountry("ST VINCENT & GRENADINES")
  case object Stateless                          extends EnumCountry("STATELESS")
  case object Sudan                              extends EnumCountry("SUDAN")
  case object Surinam                            extends EnumCountry("SURINAM")
  case object SvalbardAndJanMayen                extends EnumCountry("SVALBARD AND JAN MAYEN")
  case object Swaziland                          extends EnumCountry("SWAZILAND")
  case object Sweden                             extends EnumCountry("SWEDEN")
  case object Switzerland                        extends EnumCountry("SWITZERLAND")
  case object Syria                              extends EnumCountry("SYRIA")
  case object Tahiti                             extends EnumCountry("TAHITI")
  case object Taiwan                             extends EnumCountry("TAIWAN")
  case object Tanzania                           extends EnumCountry("TANZANIA")
  case object Thailand                           extends EnumCountry("THAILAND")
  case object Togo                               extends EnumCountry("TOGO")
  case object Tokelau                            extends EnumCountry("TOKELAU")
  case object Tonga                              extends EnumCountry("TONGA")
  case object Tours                              extends EnumCountry("TOURS")
  case object TrinidadTobago                     extends EnumCountry("TRINIDAD & TOBAGO")
  case object TristanDaCuhna                     extends EnumCountry("TRISTAN DA CUHNA")
  case object Tunisia                            extends EnumCountry("TUNISIA")
  case object Turkey                             extends EnumCountry("TURKEY")
  case object TurksCaicosIslands                 extends EnumCountry("TURKS & CAICOS ISLANDS")
  case object Tuvalu                             extends EnumCountry("TUVALU")
  case object Uganda                             extends EnumCountry("UGANDA")
  case object Ukraine                            extends EnumCountry("UKRAINE")
  case object UnitedStatesMinorOutlyingIslands   extends EnumCountry("UNITED STATES MINOR OUTLYING ISLANDS")
  case object Uruguay                            extends EnumCountry("URUGUAY")
  case object Usa                                extends EnumCountry("USA")
  case object Ussr                               extends EnumCountry("USSR")
  case object Vanuatu                            extends EnumCountry("VANUATU")
  case object VaticanCityState                   extends EnumCountry("VATICAN CITY STATE")
  case object Venezuela                          extends EnumCountry("VENEZUELA")
  case object Vietnam                            extends EnumCountry("VIETNAM")
  case object VirginIslandsBritish               extends EnumCountry("VIRGIN ISLANDS (BRITISH)")
  case object VirginIslandsUsa                   extends EnumCountry("VIRGIN ISLANDS (USA)")
  case object Wales                              extends EnumCountry("WALES")
  case object WallisAndFutuna                    extends EnumCountry("WALLIS AND FUTUNA")
  case object WesternSahara                      extends EnumCountry("WESTERN SAHARA")
  case object WesternSamoa                       extends EnumCountry("WESTERN SAMOA")
  case object Yugoslavia                         extends EnumCountry("YUGOSLAVIA")
  case object Zaire                              extends EnumCountry("ZAIRE")
  case object Zambia                             extends EnumCountry("ZAMBIA")
  case object Zimbabwe                           extends EnumCountry("ZIMBABWE")
  case object NorthernPartOfCyprus               extends EnumCountry("NORTHERN PART OF CYPRUS")
}
